services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "${PG_ADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PG_ADMIN_USER}"
      PGADMIN_DEFAULT_PASSWORD: "${PG_ADMIN_PASSWORD}"
    restart: unless-stopped

  cleanair-be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cleanair-be
    depends_on:
      - postgres
    ports:
      - "${PLAYGROUND_PORT}:4000"
    restart: always

volumes:
  db-data:
    name: "CleanAirMap-data"