import { LOCATION_TYPE } from 'common/constants';

console.log(LOCATION_TYPE.ALL);
const LOCATION_TYPES_TO_STORAGE_ID = new Map([
    [LOCATION_TYPE.ALL, 999],
    [LOCATION_TYPE.SHOP, 0],
    [LOCATION_TYPE.MUSEUM, 1],
    [LOCATION_TYPE.BAR, 2],
    [LOCATION_TYPE.CAFE, 3],
    [LOCATION_TYPE.HOSPITAL, 4],
    [LOCATION_TYPE.TRAIN, 5],
    [LOCATION_TYPE.RESTAURANT, 6],
    [LOCATION_TYPE.LIBRARY, 7],
    [LOCATION_TYPE.ARTS, 8],
    [LOCATION_TYPE.HOTEL, 9],
    [LOCATION_TYPE.GASSTATION, 10],
    [LOCATION_TYPE.PARKING, 11],
    [LOCATION_TYPE.MOVIE, 12],
    [LOCATION_TYPE.PARK, 13],
    [LOCATION_TYPE.CAMERA, 14],
    [LOCATION_TYPE.ARENA, 15],
    [LOCATION_TYPE.PHARMACY, 16],
    [LOCATION_TYPE.SCHOOL, 17],
    [LOCATION_TYPE.BEAUTY, 18],
    [LOCATION_TYPE.FITNESS, 19],
    [LOCATION_TYPE.SENIORS, 20],
    [LOCATION_TYPE.PROFESSIONAL, 21],
    [LOCATION_TYPE.DENTISTS, 22],
    [LOCATION_TYPE.DINING, 23],
    [LOCATION_TYPE.WORSHIP, 24],
]);

const LOCATION_ID_TO_TYPE = new Map([...LOCATION_TYPES_TO_STORAGE_ID].map(([k, v]) => [v, k]));

export const resolveLocationIdToType = (typeId) => {
    if (!typeId) return LOCATION_TYPE.ALL;
    return LOCATION_ID_TO_TYPE.get(typeId);
};